packages:
  - apps/*
  - apps/playground/*
  - packages/*

catalog:
  '@vitejs/plugin-vue': ^6.0.1
  eslint: 9.34.0
  typescript: 5.8.3
  unocss: ^66.5.1
  unplugin-icons: ^22.2.0
  vite: ^7.1.3
  vite-plugin-dts: ^4.5.4
  vue: ^3.5.20
  vue-tsc: 3.0.6

onlyBuiltDependencies:
  - '@parcel/watcher'
  - vue-demi
