/** @type {import("stylelint").Config} */
export default {
  extends: [
    "stylelint-config-standard",
    "stylelint-config-recommended-scss",
  ],
  plugins: [
    "stylelint-scss",
    "stylelint-order",
  ],
  rules: {
    "hue-degree-notation": "number",
    "order/properties-order": [
      "content",
      "height",
      "width",
      "margin",
      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
      "padding",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",
      "position",
      "display",
      "flex-grow",
      "flex-shrink",
      "align-items",
      "justify-content",
      "gap",
      "overflow",
      "overflow-x",
      "overflow-y",
      "border-radius",
      "color",
      "background-color",
      "box-shadow",
      "font-size",
      "transition",
      "transition-duration",
      "transition-property",
      "cursor",
      "user-select",
      "touch-action",
    ],
    "at-rule-empty-line-before": "never",
    "declaration-empty-line-before": null,
    "no-unknown-animations": true,
    "rule-empty-line-before": null,
    "unit-no-unknown": true,
    "selector-attribute-quotes": "never",
  },
};
